POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "test10@test.com",
    "auth_hash": "hash1",
    "salt": "salt1"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "test6@test.com",
    "auth_hash": "hash1",
    "code": "708903"
}