DELETE http://localhost:5000/deletePassword
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

###

DELETE http://localhost:5000/deleteNote
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

###

DELETE http://localhost:5000/deleteCreditCard
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

###

DELETE http://localhost:5000/deleteIdentity
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

###

DELETE http://localhost:5000/deleteLicense
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU
