DELETE http://localhost:5000/deletePassword
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns

###

DELETE http://localhost:5000/deleteNote
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns

###

DELETE http://localhost:5000/deleteCreditCard
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns

###

DELETE http://localhost:5000/deleteIdentity
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns

###

DELETE http://localhost:5000/deleteLicense
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns
