### Password

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU; category=Password

### Notes

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU; category=Notes

### CreditCard

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU; category=CreditCard

### Identity
PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU; category=Identity

### License
PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU; category=License
