### Password

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns; category=Password

### Notes

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns; category=Notes

### CreditCard

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns; category=CreditCard

### Identity
PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns; category=Identity

### License
PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYyM2I5ZWFiLTc2MjAtNDZlYy1iMDViLWU2MjZiODA5ZGI3NSIsImV4cCI6MTc2OTAwNDUwNH0.CleaEaKsmx9UY7ekhrW6e-lw1Ze6oHy-zA42AAUGZns; category=License
