### Password

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5N2UyMmZlLWVjYzEtNDBlNy04YTE5LThkNDY2YjhlYTUwMCIsImV4cCI6MTc2ODU3ODg4NH0.oeSOzytnrzFtg4FR45tUc5LXvEmksQS3uoWy2wfqZrA; id=01cc4cc5-e967-4f2c-93ab-db77ec07d989; category=Password

### Notes

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5N2UyMmZlLWVjYzEtNDBlNy04YTE5LThkNDY2YjhlYTUwMCIsImV4cCI6MTc2ODU3ODg4NH0.oeSOzytnrzFtg4FR45tUc5LXvEmksQS3uoWy2wfqZrA; id=50f2f632-8594-4810-aa7f-5ebe231e6502; category=Notes

### CreditCard

PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5N2UyMmZlLWVjYzEtNDBlNy04YTE5LThkNDY2YjhlYTUwMCIsImV4cCI6MTc2ODY0NTgwMn0.6vz3dHzZ7k7yVticqAhZvrk4YHBbzZuIxopUNONMXGg; id=91972609-60fe-45e9-b460-11043dca9a49; category=CreditCard

### Identity
PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5N2UyMmZlLWVjYzEtNDBlNy04YTE5LThkNDY2YjhlYTUwMCIsImV4cCI6MTc2ODU3ODg4NH0.oeSOzytnrzFtg4FR45tUc5LXvEmksQS3uoWy2wfqZrA; id=b7be96e5-d3fe-4a0b-8305-6af62c2257e6; category=Identity

### License
PUT http://localhost:5000/favourite
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY5N2UyMmZlLWVjYzEtNDBlNy04YTE5LThkNDY2YjhlYTUwMCIsImV4cCI6MTc2ODU3ODg4NH0.oeSOzytnrzFtg4FR45tUc5LXvEmksQS3uoWy2wfqZrA; id=442641fe-39cd-46d5-af39-89f67d4da219; category=License
