POST http://localhost:5000/addPassword
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

{
    "email": "added_mail1@test.co",
    "login": "added_login1",
    "password": "addedPassword",
    "domain": "google.com",
    "tfa": "hash"
}

###

POST http://localhost:5000/addNote
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

{
    "name": "added_note1",
    "content": "added_note1_content"
}

###

POST http://localhost:5000/addCreditCard
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

{
    "bankName": "added_card1",
    "number": "card_number",
    "brand": "visa",
    "cvv": "711",
    "owner": "Owner 1",
    "exp_date": "2003/12"
}

###

POST http://localhost:5000/addIdentity
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

{
    "name": "name1",
    "surname": "surname1",
    "country": "country1",
    "state": "state1",
    "city": "city1",
    "street": "street1",
    "number": "28"
}

###

POST http://localhost:5000/addLicense
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZiM2Q2MWRmLWU1ZWMtNDMyOS1iMzM5LWRlNDBhYWRhNzAxOCIsImV4cCI6MTc2OTQzNjQxNn0.16WSIWZl3zrhlUlgWNYATvwpe64drjAyjPY0g6TffYU

{
    "name": "name1",
    "diverse": "{\"number\" : \"0\"}"
}